volumes:
  mysql:
  keycloakdb:

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - "8747:8080"

  keycloakdb:
    image: postgres:15
    volumes:
      - keycloakdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  mysql:
    image: mysql:8.4.2
    environment:
      MYSQL_USER: ideashare
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: ideashare
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3318:3306"